Style:
  Enabled: false

# Include: **/Gemfile, **/gems.rb
Bundler/OrderedGems:
  Exclude:
    - 'Gemfile'

# Configuration parameters: EnforcedStyle, SupportedStyles.
# SupportedStyles: nested, compact
Style/ClassAndModuleChildren:
  Exclude:
    - 'test/test_helper.rb'

Style/Documentation:
  Exclude:
    - 'spec/**/*'
    - 'test/**/*'
    - 'node_modules/*'
    - 'app/controllers/application_controller.rb'
    - 'app/helpers/application_helper.rb'
    - 'app/mailers/application_mailer.rb'
    - 'app/models/application_record.rb'

# Configuration parameters: PreferredDelimiters.
Style/PercentLiteralDelimiters:
  Exclude:
    - 'config/spring.rb'

# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles, ConsistentQuotesInMultiline.
# SupportedStyles: single_quotes, double_quotes
Style/StringLiterals:
  Exclude:
    - 'Gemfile'
    - 'bin/spring'
    - 'config/environments/production.rb'
    - 'config/puma.rb'

# Cop supports --auto-correct.
# Configuration parameters: SupportedStyles.
# SupportedStyles: percent, brackets
Style/SymbolArray:
  EnforcedStyle: brackets

AllCops:
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'test/**/*'
    - 'lib/**/*'
    - 'spec/**/*'
    - 'app/views/**/*.json.jbuilder'
    - 'node_modules/**/*'
    - 'bin/**/*'
    - 'Rakefile'